### ISSUE TITLE
Linux binary distribution is broken

### ISSUE THREAD

**Issue by mobilinkd** [maqifrnswa/PCSI#9]
The Linux binary distribution appears to be missing some of the TK and/or PIL components.  This results in the following error

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "PIL/ImageTk.py", line 182, in paste
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "pcsiGUI.py", line 148, in loadfile
  File "PIL/ImageTk.py", line 121, in __init__
  File "PIL/ImageTk.py", line 186, in paste
ModuleNotFoundError: No module named 'PIL._tkinter_finder'
```

I am running this on Fedora 31.

**Comment by mobilinkd** [comment]
To follow up on this, building from source worked as expected.
